language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
after_success:
  - source deploy.sh 
deploy:
  name: $NAME
  email: $EMAIL
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
